bluecadet_file_struct.settings:
  type: config_object
  label: 'File struct Config settings'
  mapping:
    media_field:
      type: mapping
      label: 'Media Field to act on'
      mapping:
        type: string
        label: 'Field'
    public_vocab:
      type: mapping
      label: 'Vacabulary which represents the directory structure for public files.'
      mapping:
        type: string
        label: 'Vocabulary ID'
    private_vocab:
      type: mapping
      label: 'Vacabulary which represents the directory structure for private files.'
      mapping:
        type: string
        label: 'Vocabulary ID'
